* Configure use-package
** Setup archives
#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives '("gnu"   . "https://elpa.gnu.org/packages/"))
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
#+END_SRC
** Ensure installed
#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
(package-refresh-contents)
(package-install 'use-package))
(eval-and-compile
(setq use-package-always-ensure t
  use-package-expand-minimally t))
#+END_SRC
* Installing packages
** Evil Mode
I'm using both Evil and Evil collection, as it's better than just evil.
We will enable some configurations, thus making it a bit better.
#+BEGIN_SRC emacs-lisp
(use-package evil
  :ensure t
  :init
  (setq evil-want-keybinding nil)
  (setq evil-vsplit-window-right t)
  (setq evil-want-C-u-scroll t)
  (setq evil-split-window-below t)
  (evil-mode))
(use-package evil-collection
  :after evil
  :ensure t
  :config
  (evil-collection-init))
#+END_SRC
** Themes
I typically use the Dracula theme, but its good to mix.
#+BEGIN_SRC emacs-lisp
(use-package dracula-theme
  :ensure t)
(use-package catppuccin-theme
  :ensure t)
(use-package nord-theme
  :ensure t)
(use-package doom-themes
  :ensure t)
#+END_SRC
** General
General gives us some nice features for other packages.
#+BEGIN_SRC emacs-lisp
(use-package general
  :ensure t
  :config
  (general-evil-setup t))
#+END_SRC
** All The Icons
Just a simple icon plugin
#+BEGIN_SRC emacs-lisp
(use-package all-the-icons
  :if (display-graphic-p))
#+END_SRC
** Haskell
#+BEGIN_SRC emacs-lisp
(use-package haskell-mode
  :ensure t)
(use-package hindent
  :ensure t)
(add-hook 'haskell-mode-hook #'hindent-mode)
#+END_SRC
** Projectile
#+BEGIN_SRC emacs-lisp
(use-package projectile
  :config
  (projectile-global-mode 1))
#+END_SRC
** Treesitter
#+BEGIN_SRC emacs-lisp
(use-package tree-sitter
  :ensure t)
(use-package tree-sitter-langs
  :ensure t)
#+END_SRC
** Dashboard
Here I'll just do all the configurations inside the init block.
#+BEGIN_SRC emacs-lisp
(use-package dashboard
  :init      ;; tweak dashboard config before loading it
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-banner-logo-title "real programmers use vi")
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "~/.emacs.d/.local/logo.png")  ;; use custom image as banner
  (setq dashboard-center-content t) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (agenda . 5 )
                          (bookmarks . 3)
                          (projects . 3)))
  :config
  (dashboard-setup-startup-hook)
  (dashboard-modify-heading-icons '((recents . "file-text")
			      (bookmarks . "book"))))
#+END_SRC
** Everything for a better M-x
#+BEGIN_SRC emacs-lisp
(use-package smex
  :ensure t
  :config
  (smex-initialize))
(use-package vertico
  :ensure t
  :bind (:map vertico-map
	      ("C-j" . vertico-next)
	      ("C-k" . vertico-previous)
	      ("C-f" . vertico-exit))
  :custom
  (vertico-cycle t)
  :init
  (vertico-mode))
(use-package marginalia
  :after vertico
  :ensure t
  :custom
  (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil))
  :init
  (marginalia-mode))
#+END_SRC
** Which-key
Which key helps with 'definitions' for functions
#+BEGIN_SRC emacs-lisp
(use-package which-key
    :config
    (which-key-mode))
#+END_SRC
** Doom Modeline
#+BEGIN_SRC emacs-lisp
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1))
#+END_SRC
* Configurations
** General configurations
*** Set short answers
#+BEGIN_SRC emacs-lisp
(setq use-short-answers t)
#+END_SRC
*** Disable backup files
#+BEGIN_SRC emacs-lisp
(setq make-backup-files nil)
#+END_SRC
*** Disabling bars
#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
(menu-bar-mode -1)
(tab-bar-mode -1)
(scroll-bar-mode -1)
#+END_SRC
*** Setting Font and themes
#+BEGIN_SRC emacs-lisp
(setq doom-themes-enable-bold t
	doom-themes-enable-italic t)
(load-theme 'doom-dracula t)
(add-to-list 'default-frame-alist '(font . "Inconsolata-18"))
#+END_SRC
*** Setting warning level
#+BEGIN_SRC emacs-lisp
(setq warning-minimum-level :emergency)
#+END_SRC
*** Line numbers
#+BEGIN_SRC emacs-lisp
(when (version<= "26.0.50" emacs-version )
  (global-display-line-numbers-mode))
(setq display-line-numbers-type 'relative)
#+END_SRC
*** Load dashboard with emacsclient
#+BEGIN_SRC emacs-lisp
(setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")))
#+END_SRC
*** Set temp directory
#+BEGIN_SRC emacs-lisp
(setq temporary-file-directory "~/.tmp/")
 (setq backup-directory-alist
      `((".*" . ,temporary-file-directory)))
#+END_SRC
**** Here we will also set auto save to nil
#+BEGIN_SRC emacs-lisp
(setq auto-save-default nil)
#+END_SRC
*** Vim like insert TABs
#+BEGIN_SRC emacs-lisp
(define-key evil-insert-state-map (kbd "TAB") 'tab-to-tab-stop)
#+END_SRC
*** Tabs
#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq indent-line-function 'insert-tab)
#+END_SRC
** General Keybinds
*** C-c remap
I personally like doing this, though it will break some stuff, so you probably shouldn't use it
#+BEGIN_SRC emacs-lisp
(define-key evil-insert-state-map (kbd "C-c") 'evil-normal-state)
(define-key evil-normal-state-map (kbd "C-c") 'evil-normal-state)
(define-key key-translation-map (kbd "C-c C-c") (kbd "C-g"))
#+END_SRC
*** SPC commands
These are just some doom emacs keybinds I like having
#+BEGIN_SRC emacs-lisp
(nvmap :prefix "SPC"
  "t n"   '(neotree-toggle :which-key "Toggle neotree file viewer")
  "d n"   '(neotree-dir :which-key "Open directory in neotree"))
(nvmap :keymaps 'override :prefix "SPC"
  "SPC"   '(counsel-M-x :which-key "M-x")
  "."     '(find-file :which-key "Find file") 
  "c c"   '(compile :which-key "Compile")
  "f f"   '(dirvish :which-key "Dirvish")
  "c C"   '(recompile :which-key "Recompile")
  "h r r" '((lambda () (interactive) (load-file "~/.emacs.d/init.el")) :which-key "Reload emacs config")
  "t t"   '(toggle-truncate-lines :which-key "Toggle truncate lines"))
(nvmap :prefix "SPC"
  "b b"   '(ibuffer :which-key "Ibuffer")
  "b c"   '(clone-indirect-buffer-other-window :which-key "Clone indirect buffer other window")
  "b k"   '(kill-current-buffer :which-key "Kill current buffer")
  "b n"   '(next-buffer :which-key "Next buffer")
  "b p"   '(previous-buffer :which-key "Previous buffer")
  "b B"   '(ibuffer-list-buffers :which-key "Ibuffer list buffers")
  "b K"   '(kill-buffer :which-key "Kill buffer")
  "r f"   '(dashboard-refresh-buffer :which-key "Refresh buffer"))
#+END_SRC
*** Evil mode undo/redo
#+BEGIN_SRC emacs-lisp
(define-key evil-normal-state-map "u" 'evil-undo)
(define-key evil-normal-state-map (kbd "C-r") 'undo-tree-redo)
#+END_SRC
** Doom modeline config
  #+BEGIN_SRC emacs-lisp
  (setq doom-modeline-time-icon t)
  (setq doom-modeline-icon t)
  (setq doom-modeline-buffer-file-name-style 'auto)
  (setq doom-modeline-buffer-name t)
  (setq doom-modeline-indent-info nil)
  (setq doom-modeline-buffer-encoding t)
  (setq doom-modeline-enable-word-count nil)
  #+END_SRC
** Custom functions
*** Disable quit with evil mode :q and :wq
#+BEGIN_SRC emacs-lisp
(defun save-and-kill-this-buffer()
  "Quits the buffer"
  (interactive)
  (save-buffer)
  (kill-current-buffer))
(defun quit-buffer()
  "Quits the buffer"
  (interactive)
  (kill-current-buffer))
#+END_SRC
And here are the keybinds
#+BEGIN_SRC emacs-lisp
(evil-ex-define-cmd "wq" 'save-and-kill-this-buffer)
(evil-ex-define-cmd "q" 'quit-buffer)
#+END_SRC
*** Autopairs
#+BEGIN_SRC emacs-lisp
(defun electric-pair ()
  "Autoconnects a given char with another"
  (interactive)
  (if (eolp) (let (parens-require-spaces) (insert-pair)) (self-insert-command 1)))
#+END_SRC
And here are the hooks we define.
#+BEGIN_SRC emacs-lisp
(add-hook 'c-mode-hook
          (lambda ()
            (define-key c-mode-map "\"" 'electric-pair)
            (define-key c-mode-map "\'" 'electric-pair)
            (define-key c-mode-map "(" 'electric-pair)
            (define-key c-mode-map "[" 'electric-pair)
            (define-key c-mode-map "{" 'electric-pair)))
(add-hook 'lisp-mode-hook
          (lambda ()
            (define-key lisp-mode-map "\"" 'electric-pair)
            (define-key lisp-mode-map "\'" 'electric-pair)
            (define-key lisp-mode-map "(" 'electric-pair)
            (define-key lisp-mode-map "[" 'electric-pair)
            (define-key lisp-mode-map "{" 'electric-pair)))
(add-hook 'scheme-mode-hook
          (lambda ()
            (define-key scheme-mode-map "\"" 'electric-pair)
            (define-key scheme-mode-map "\'" 'electric-pair)
            (define-key scheme-mode-map "(" 'electric-pair)
            (define-key scheme-mode-map "[" 'electric-pair)
            (define-key scheme-mode-map "{" 'electric-pair)))
(add-hook 'haskell-mode-hook
          (lambda ()
            (define-key haskell-mode-map "\"" 'electric-pair)
            (define-key haskell-mode-map "\'" 'electric-pair)
            (define-key haskell-mode-map "(" 'electric-pair)
            (define-key haskell-mode-map "[" 'electric-pair)
            (define-key haskell-mode-map "{" 'electric-pair)))
#+END_SRC
*** Garbage Collection
#+BEGIN_SRC emacs-lisp
(defun my-gc-function ()
  (setq gc-cons-threshold 800000)
  (defun my-gc-function ()
    (garbage-collect)))
#+END_SRC
And here is the hook for it.
#+BEGIN_SRC emacs-lisp
(add-hook 'focus-out-hook #'my-gc-function)
#+END_SRC
